

name: Fetch Artifacts and Create Release

# 触发条件：可以根据需要修改，例如定时触发或手动触发
on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 */6 * * *'  # 6h/次

jobs:
  fetch-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up environment
        run: |
          mkdir -p artifacts downloads
      
      - name: Download artifacts from source repository
        uses: dawidd6/action-download-artifact@v3
        with:
          # 替换为源仓库的所有者和仓库名
          repo: Shopkeepers/Shopkeepers
          # 源仓库的工作流文件名或ID
          workflow: build.yml
          # 分支名，默认为main
          branch: master
          # 使用正确的参数名 workflow_conclusion 替代 status
          workflow_conclusion: success
          # 下载路径
          path: ./downloads
          # 必须提供github_token参数
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Unzip artifacts
        run: |
          # 解压所有下载的zip文件到artifacts目录
          for file in ./downloads/**/*.zip; do
            unzip -d ./artifacts "$file"
          done
      
      - name: Get current date for release tag
        id: date
        run: echo "::set-output name=tag::release-$(date +'%Y%m%d')"
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.date.outputs.tag }}
          name: Automated Release ${{ steps.date.outputs.tag }}
          body: |
            This is an automated release containing artifacts from the source repository.
            Generated on: ${{ github.event.head_commit.timestamp }}
          files: |
            ./artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
