

name: Fetch Artifacts and Create Release

# 触发条件：可以根据需要修改，例如定时触发或手动触发
on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 */6 * * *'  # 6h/次

jobs:
  fetch-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up environment
        run: |
          mkdir -p artifacts selected
      
      - name: Download artifacts from source repository
        uses: dawidd6/action-download-artifact@v3
        with:
          repo: Shopkeepers/Shopkeepers
          workflow: build.yml
          branch: master
          workflow_conclusion: success
          path: ./artifacts
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: List all downloaded files (for debugging)
        run: |
          echo "All downloaded files:"
          find ./artifacts -type f
      
      - name: Select only Shopkeepers-*-SNAPSHOT.jar files
        id: select_jar
        run: |
          # 查找符合命名模式的JAR文件
          JAR_FILE=$(find ./artifacts -name "Shopkeepers-*-SNAPSHOT.jar" | head -n 1)
          
          # 检查是否找到文件
          if [ -z "$JAR_FILE" ]; then
            echo "Error: No Shopkeepers-*-SNAPSHOT.jar file found!"
            exit 1
          fi
          
          # 复制选中的文件到单独目录
          cp "$JAR_FILE" ./selected/
          
          # 提取版本号
          VERSION=$(basename "$JAR_FILE" | sed -E 's/Shopkeepers-(.*)\.jar/\1/')
          echo "Found version: $VERSION"
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=jar_path::$JAR_FILE"
      
      - name: List selected files
        run: |
          echo "Selected files to release:"
          find ./selected -type f
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ steps.select_jar.outputs.version }}
          name: Release ${{ steps.select_jar.outputs.version }}
          body: |
            This is an automated release containing the Shopkeepers snapshot build.
            Version: ${{ steps.select_jar.outputs.version }}
            Generated on: ${{ github.event.head_commit.timestamp }}
          files: |
            ./selected/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
