

name: Fetch Artifacts and Create Release

# 触发条件：可以根据需要修改，例如定时触发或手动触发
on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 */6 * * *'  # 6h/次

jobs:
  fetch-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up environment
        run: |
          mkdir -p artifacts selected
      
      - name: Generate random string
        id: random
        run: |
          # 生成8位随机字母数字字符
          RANDOM_STR=$(openssl rand -hex 4)
          echo "::set-output name=str::$RANDOM_STR"
          # 也可以使用时间戳作为替代方案
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          echo "::set-output name=timestamp::$TIMESTAMP"
      
      - name: Download artifacts from source repository
        uses: dawidd6/action-download-artifact@v3
        with:
          repo: Shopkeepers/Shopkeepers
          workflow: build.yml
          branch: master
          workflow_conclusion: success
          path: ./artifacts
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Select only Shopkeepers-*-SNAPSHOT.jar files
        id: select_jar
        run: |
          # 查找符合命名模式的JAR文件
          JAR_FILE=$(find ./artifacts -name "Shopkeepers-*-SNAPSHOT.jar" | head -n 1)
          
          # 检查是否找到文件
          if [ -z "$JAR_FILE" ]; then
            echo "Error: No Shopkeepers-*-SNAPSHOT.jar file found!"
            exit 1
          fi
          
          # 复制选中的文件到单独目录
          cp "$JAR_FILE" ./selected/
          
          # 提取基础版本号
          BASE_VERSION=$(basename "$JAR_FILE" | sed -E 's/Shopkeepers-(.*)\.jar/\1/')
          echo "Base version: $BASE_VERSION"
          echo "::set-output name=base_version::$BASE_VERSION"
          echo "::set-output name=jar_path::$JAR_FILE"
      
      - name: Create unique version and tag
        id: version
        run: |
          # 结合基础版本号、随机字符串和时间戳确保唯一性
          UNIQUE_VERSION="${{ steps.select_jar.outputs.base_version }}-${{ steps.random.outputs.timestamp }}-${{ steps.random.outputs.str }}"
          echo "::set-output name=unique_version::$UNIQUE_VERSION"
          echo "::set-output name=tag::release-$UNIQUE_VERSION"
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Release ${{ steps.version.outputs.unique_version }}
          body: |
            This is an automated release containing the Shopkeepers snapshot build.
            Base Version: ${{ steps.select_jar.outputs.base_version }}
            Unique Version: ${{ steps.version.outputs.unique_version }}
            Generated on: ${{ github.event.head_commit.timestamp }}
          files: |
            ./selected/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
